### ISSUE TITLE
How create a desktop shortcut?

### ISSUE THREAD

**Issue by Uploadsgit** [tksh164/alter-rdp-client#71]
Hi! this client is insane congrats!

but is possible make a shortcut with credentials to autologin? thanks mate and have nice day :)

**Comment by tksh164** [comment]
Thank you @Uploadsgit for using Alter and feedback.

Difficult to create a shortcut because the current version of Alter does not support any command-line options. But the next release of Alter will support it then, can create a shortcut. Stay tuned👍

**Comment by tksh164** [comment]
Hi @Uploadsgit, [Alter v0.5.0](https://github.com/tksh164/alter-rdp-client/releases/tag/v0.5.0) supports command-line options now. So, you can create shortcuts with auto-login.

**Command-line options:**

```
Alter.exe [-host:<RemoteHost>] [-port:<Port>] [-username:<UserName>] [-title:<Title>] [-autoconnect]
````

- `-host` - Specify the remote host's DNS name or IP address to which you want to connect.
    - Example: `-host:host1.example.com`
    - Example: `-host:198.51.100.123`

- `-port` - Specify the remote port to which you use to connect. Use the default port (3389) if not specified.
    - Example: `-port:12345`

- `-username` - Specify the user name that you want to use to connect to the remote host. Enclose the user name in double quotes if it has whitespaces.
    - Example: `-username:UserName`
    - Example: `-username:"User Name"`

- `-title` - Specify the title for the connection. Enclose the title in double quotes if it has whitespaces.
    - Example: `-title:JumpboxServer`
    - Example: `-title:"Jumpbox Server"`

- `-autoconnect` - If specify this option, will automatically start the connection.

Also, Alter does not store any credentials because it is not easy to store safely. However, Windows can store your credentials safely. That is easy, just check the `Remember me` at the first time. Then you can skip enter credentials next time.

![image](https://github.com/tksh164/alter-rdp-client/assets/1618784/6afb29e4-1679-4a7c-8223-e92cc68cbdcb)

![](https://raw.githubusercontent.com/tksh164/whatnot/main/alter/media/alter-auto-connecting-demo.gif)
